INSERT INTO APP.LOCATION (LOCATION_ID,LOCATION_NM,"location address",ROW_VERSION) VALUES (
1,'SALEM COMMUNITY HALL','SALEM,OREGON',0);

INSERT INTO APP.USER_DETAIL (USER_ID,USERNAME,ROW_VERSION) VALUES (
1,'username@username.com',0);

INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
1,'A1',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
2,'A2',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
3,'A3',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
4,'A4',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
5,'A5',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
6,'A6',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
7,'A7',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
8,'A8',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
9,'A9',0,1);
INSERT INTO APP.AVAILABLE_SEATS (SEAT_ID,SEAT_LOCATION,VERSION_ID,LOCATION_ID) VALUES (
10,'A10',0,1);

INSERT INTO APP.EVENT (EVENT_ID,EVENT_NM,ROW_VERSION,LOCATION_ID) VALUES (
1,'SCHOOL FUNCTION',0,1);
