-- Drop table

-- DROP TABLE APP.AVAILABLE_SEATS

CREATE TABLE APP.AVAILABLE_SEATS (
	SEAT_ID BIGINT NOT NULL,
	SEAT_LOCATION VARCHAR(255),
	VERSION_ID INTEGER,
	LOCATION_ID BIGINT,
	CONSTRAINT SQL190828214736620 PRIMARY KEY (SEAT_ID),
	CONSTRAINT FKBSEH08B6NU38P0GA3F3QF7K5R FOREIGN KEY (LOCATION_ID) REFERENCES APP.LOCATION(LOCATION_ID)
);
CREATE INDEX SQL190828214736660 ON APP.AVAILABLE_SEATS (LOCATION_ID);

-- Drop table

-- DROP TABLE APP.EVENT

CREATE TABLE APP.EVENT (
	EVENT_ID BIGINT NOT NULL,
	EVENT_NM VARCHAR(255),
	ROW_VERSION INTEGER,
	LOCATION_ID BIGINT,
	CONSTRAINT SQL190828214736630 PRIMARY KEY (EVENT_ID),
	CONSTRAINT FKBB6C0H5NHS5OG47IEM617EHRL FOREIGN KEY (LOCATION_ID) REFERENCES APP.LOCATION(LOCATION_ID)
);
CREATE INDEX SQL190828214736661 ON APP.EVENT (LOCATION_ID);

-- Drop table

-- DROP TABLE APP.LOCATION

CREATE TABLE APP.LOCATION (
	LOCATION_ID BIGINT NOT NULL,
	LOCATION_NM VARCHAR(255),
	LOCATION_ADDRESS VARCHAR(255),
	ROW_VERSION INTEGER,
	CONSTRAINT SQL190828214736631 PRIMARY KEY (LOCATION_ID)
);

-- Drop table

-- DROP TABLE APP.LOCATION_SEAT_HOLD

CREATE TABLE APP.LOCATION_SEAT_HOLD (
	EVENT_ID BIGINT NOT NULL,
	HOLD_ID BIGINT NOT NULL,
	LOCATION_ID BIGINT NOT NULL,
	SEAT_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	EXPIRATION_TIMESTAMP TIMESTAMP,
	ROW_VERSION INTEGER,
	CONSTRAINT SQL190828214736640 PRIMARY KEY (EVENT_ID,HOLD_ID,LOCATION_ID,SEAT_ID,USER_ID),
	CONSTRAINT FK1H5WWVWFRT20WWSAME2BPUONX FOREIGN KEY (LOCATION_ID) REFERENCES APP.LOCATION(LOCATION_ID),
	CONSTRAINT FK2XO0CUI717P2YN70UEXKVFKT2 FOREIGN KEY (EVENT_ID) REFERENCES APP.EVENT(EVENT_ID),
	CONSTRAINT FK7MF87HNX54AAKS2TAULGNGYAN FOREIGN KEY (SEAT_ID) REFERENCES APP.AVAILABLE_SEATS(SEAT_ID),
	CONSTRAINT FKFWD0TH0VUEWOS2KTIC52JJILE FOREIGN KEY (USER_ID) REFERENCES APP.USER_DETAIL(USER_ID)
);
CREATE INDEX SQL190828214736662 ON APP.LOCATION_SEAT_HOLD (SEAT_ID);
CREATE INDEX SQL190828214736670 ON APP.LOCATION_SEAT_HOLD (EVENT_ID);
CREATE INDEX SQL190828214736680 ON APP.LOCATION_SEAT_HOLD (LOCATION_ID);
CREATE INDEX SQL190829032308670 ON APP.LOCATION_SEAT_HOLD (USER_ID);

-- Drop table

-- DROP TABLE APP.LOCATION_SEAT_RESERVATION

CREATE TABLE APP.LOCATION_SEAT_RESERVATION (
	RESERVATION_ID BIGINT NOT NULL,
	ROW_VERSION INTEGER,
	EVENT_ID BIGINT,
	HOLD_ID BIGINT,
	LOCATION_ID BIGINT,
	SEAT_ID BIGINT,
	USER_ID BIGINT,
	CONFIRM_CODE VARCHAR(100) DEFAULT '' NOT NULL,
	CONSTRAINT SQL190828214736650 PRIMARY KEY (RESERVATION_ID),
	CONSTRAINT FK9DOQEY1UKLRLVYVHONVT0BNCI FOREIGN KEY (EVENT_ID,HOLD_ID,LOCATION_ID,SEAT_ID,USER_ID) REFERENCES APP.LOCATION_SEAT_HOLD(EVENT_ID,HOLD_ID,LOCATION_ID,SEAT_ID,USER_ID),
	CONSTRAINT LOCATION_SEAT_RESERVATION_AVAILABLE_SEATS_FK FOREIGN KEY (SEAT_ID) REFERENCES APP.AVAILABLE_SEATS(SEAT_ID),
	CONSTRAINT LOCATION_SEAT_RESERVATION_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES APP.EVENT(EVENT_ID),
	CONSTRAINT LOCATION_SEAT_RESERVATION_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES APP.LOCATION(LOCATION_ID),
	CONSTRAINT LOCATION_SEAT_RESERVATION_USER_FK FOREIGN KEY (USER_ID) REFERENCES APP.USER_DETAIL(USER_ID)
);
CREATE INDEX SQL190828214736710 ON APP.LOCATION_SEAT_RESERVATION (EVENT_ID,HOLD_ID,LOCATION_ID,SEAT_ID,USER_ID);
CREATE INDEX SQL190828215154930 ON APP.LOCATION_SEAT_RESERVATION (EVENT_ID);
CREATE INDEX SQL190828215154940 ON APP.LOCATION_SEAT_RESERVATION (SEAT_ID);
CREATE INDEX SQL190828215154950 ON APP.LOCATION_SEAT_RESERVATION (LOCATION_ID);
CREATE INDEX SQL190828215154960 ON APP.LOCATION_SEAT_RESERVATION (USER_ID);

-- Drop table

-- DROP TABLE APP.USER_DETAIL

CREATE TABLE APP.USER_DETAIL (
	USER_ID BIGINT NOT NULL,
	USERNAME VARCHAR(100),
	ROW_VERSION INTEGER NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX SQL190828012902850 ON APP.USER_DETAIL (USER_ID);


CREATE SEQUENCE APP.AVAILABLE_SEATS_SEATID_GENERATOR
AS BIGINT
START WITH 3000000000;

CREATE SEQUENCE APP.EVENT_EVENTID_GENERATOR
AS BIGINT
START WITH 3000000000;

CREATE SEQUENCE APP.LOCATION_LOCATIONID_GENERATOR
AS BIGINT
START WITH 3000000000;

CREATE SEQUENCE APP.SEAT_HOLD_ID_GENERATOR
AS BIGINT
START WITH 3000000000;

CREATE SEQUENCE APP.LOCATION_SEAT_RESERVATION_RESERVATIONID_GENERATOR
AS BIGINT
START WITH 3000000000;

CREATE SEQUENCE APP.USER_USERID_GENERATOR
AS BIGINT
START WITH 3000000000;

